# Generated by Django 4.2.7 on 2025-09-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
    ]
